services:
  todoapi:
    build:
      context: ./todoapi
      dockerfile: Dockerfile
    image: todoapi:latest
    container_name: todoapi
    ports:
     - "8080:8080"
  postgres:
    image: postgres:16-alpine
    container_name: fitness_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: your_secure_password_here
      POSTGRES_DB: fitness_tracker
      POSTGRES_INITDB_ARGS: "-E UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitness_user -d fitness_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local